// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: createopenedpost.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createOpenedPost = `-- name: CreateOpenedPost :one
INSERT INTO opened (id, opened_at, user_id, feed_id, post_id)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5
)
RETURNING id, opened_at, user_id, feed_id, post_id
`

type CreateOpenedPostParams struct {
	ID       uuid.UUID
	OpenedAt time.Time
	UserID   uuid.UUID
	FeedID   uuid.UUID
	PostID   uuid.UUID
}

func (q *Queries) CreateOpenedPost(ctx context.Context, arg CreateOpenedPostParams) (Opened, error) {
	row := q.db.QueryRowContext(ctx, createOpenedPost,
		arg.ID,
		arg.OpenedAt,
		arg.UserID,
		arg.FeedID,
		arg.PostID,
	)
	var i Opened
	err := row.Scan(
		&i.ID,
		&i.OpenedAt,
		&i.UserID,
		&i.FeedID,
		&i.PostID,
	)
	return i, err
}
