// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: getfeedposts.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const getFeedPosts = `-- name: GetFeedPosts :many
SELECT
    p.id,
    p.created_at,
    p.updated_at,
    p.title,
    p.url,
    p.description,
    p.published_at,
    p.feed_id 
FROM posts as p
LEFT JOIN feed_follows as ff
    ON ff.feed_id = p.feed_id
WHERE 
    ff.user_id = $1
    AND p.feed_id = $2
ORDER BY 
    p.published_at DESC
`

type GetFeedPostsParams struct {
	UserID uuid.UUID
	FeedID uuid.UUID
}

func (q *Queries) GetFeedPosts(ctx context.Context, arg GetFeedPostsParams) ([]Post, error) {
	rows, err := q.db.QueryContext(ctx, getFeedPosts, arg.UserID, arg.FeedID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Post
	for rows.Next() {
		var i Post
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Title,
			&i.Url,
			&i.Description,
			&i.PublishedAt,
			&i.FeedID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
