// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: getopenedposts.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const getOpenedPost = `-- name: GetOpenedPost :many
SELECT 
    id,
    opened_at,
    user_id,
    feed_id,
    post_id
FROM opened
WHERE 
    user_id = $1
`

func (q *Queries) GetOpenedPost(ctx context.Context, userID uuid.UUID) ([]Opened, error) {
	rows, err := q.db.QueryContext(ctx, getOpenedPost, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Opened
	for rows.Next() {
		var i Opened
		if err := rows.Scan(
			&i.ID,
			&i.OpenedAt,
			&i.UserID,
			&i.FeedID,
			&i.PostID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
