// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: getunreadcount.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const getUnreadCount = `-- name: GetUnreadCount :one
SELECT COUNT(*) FROM posts p
JOIN feed_follows ff ON p.feed_id = ff.feed_id
LEFT JOIN opened o
  ON o.post_id = p.id AND o.user_id = ff.user_id
WHERE
  ff.user_id = $1
  AND ff.feed_id = $2
  AND o.id IS NULL
  AND p.published_at > ff.created_at
`

type GetUnreadCountParams struct {
	UserID uuid.UUID
	FeedID uuid.UUID
}

func (q *Queries) GetUnreadCount(ctx context.Context, arg GetUnreadCountParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, getUnreadCount, arg.UserID, arg.FeedID)
	var count int64
	err := row.Scan(&count)
	return count, err
}
